lib/cli/Shell.php
`cli\Shell::columns()` now supports Windows environments by parsing the output of `mode`
=> Add retrieval of shell column length on Windows

lib/cli/Shell.php
This patch fixes the warning displayed when `exec` is set in `disable_functions` directive.
`Warning: exec() has been disabled for security reasons in vendor/wp-cli/php-cli-tools/lib/cli/Shell.php on line 32`
If exec is disabled, `$columns` will assume the value set here: https://github.com/tiagohillebrandt/php-cli-tools/blob/master/lib/cli/Shell.php#L44,L46
=> Verifies if exec is not in disable_functions directive

tests/test-table-ascii.php
Test cases that rely on assertOutFileEqualsWith will currently label the actual, and expected elements of the test results incorrectly. The "actual" results will be labelled as the "expected" results and vice versa.
The function currently relies on assertStringEqualsFile from PHPUnit (http://apigen.juzna.cz/doc/sebastianbergmann/phpunit/function-assertStringEqualsFile.html). This relies on the "expected" results being in the file, and the "actual" results being passed as a string. In this case however, the "actual" results are in the file, and the "expected" results are in the string. 
This PR no longer users assertStringEqualsFile, instead using assertEquals and gets the arguments in the correct place.
=> Make "Expected" and "Actual" label the correct outputs in test results

lib/cli/Colors.php, tests/test-table-ascii.php
This prevents true percent + space combinations from losing the space.
Reported in https://github.com/wp-cli/wp-cli/issues/1736
=> Use a more impossible placeholder pattern in `Colors::colorize()`

lib/cli/cli.php, tests/test-table-ascii.php
If we're not colorizing, we should be calculating padding based on the
original string.
=> Only decolorize in `cli\safe_str_pad()` when colorizing

examples/common.php
If php-cli-tools added in some project using `composer require wp-cli/php-cli-tools` then examples scripts will not work because path to `/vendor/autoload.php` will be different from path used in `/examples/common.php`.
=> Fix Composer autoload path in examples

lib/cli/Arguments.php, tests/test-arguments.php
Reverts wp-cli/php-cli-tools#97
=> Revert "always populate parsed arguments with default values"

lib/cli/Arguments.php, tests/test-arguments.php
"always populate parsed arguments with default values" was implemented in PR https://github.com/wp-cli/php-cli-tools/pull/97 but reverted later because of a failing test. 
This PR brings the feature back (revert the revert) and fixes the failing test. The fix is very small and can be reviewed in https://github.com/Luxian/php-cli-tools/commit/f5080ac86b9719b2a732180a55b809e0b247fffa
Closes issue #30
=> Bring back default values and fix tests

lib/cli/Shell.php, tests/test-shell.php
Issue https://github.com/wp-cli/wp-cli/issues/4127
Caters for bash-like shells on Windows that return incorrect columns using `mode CON`.
Checks that `TERM` env var exists before using `tput` otherwise it will write stuff to STDERR, which messes up tests.
Makes testable with env var `WP_CLI_TEST_SHELL_COLUMNS_RESET` to reset the `$columns` static.
Uses `function_exists()` rather than checking `disable_functions` ini directive as it's more reliable (though to be totally correct should also check suhosin whitelist/blacklist).
Parses output of `mode CON` in a locale-indifferent way.
=> Shell:columns(): Better calc on Windows. Check TERM. Make testable.

lib/cli/Colors.php, lib/cli/Table.php, lib/cli/cli.php, lib/cli/table/Ascii.php, tests/test-cli.php, tests/test-table.php
PR https://github.com/wp-cli/php-cli-tools/pull/109 and issue https://github.com/wp-cli/php-cli-tools/issues/106
For PR https://github.com/wp-cli/php-cli-tools/pull/109 (incorrect wrapping of East Asian double-width chars in tables), adds an `is_width` arg to `safe_substr()` to make it interpret the `length` arg as a spacing width, and uses the East Asian Width regex (now refactored to load in a function) to adjust accordingly (a slow algorithm but couldn't think of anything better). Uses this in `Ascii::row()`.
For issue https://github.com/wp-cli/php-cli-tools/issues/106 (related https://github.com/wp-cli/wp-cli/pull/2458), adds `pre_colorized` arg to various functions, and adds `Ascii::set/isPreColorized()` and `Table::set/isAsciiPreColorize()` (the latter to be used via a corresponding …
=> PR 109 (double-width wrapping) and issue 106 (pre-colorization).

lib/cli/Shell.php
Fixes #112 
In `Shell::columns()` uses the `COLUMNS` environment variable first if available, and suppresses any errors on invoking `tput` by redirecting to `/dev/null`.
Didn't bother with trying `stty` as `COLUMNS` should basically always work I think.
=> Suppress tput stderr. Use COLUMNS env var 1st if available.

lib/cli/cli.php, lib/cli/table/Ascii.php, tests/test-cli.php, tests/test-table.php
Related https://github.com/wp-cli/php-cli-tools/pull/111
Looking at the @miya0001's test table at https://github.com/wp-cli/php-cli-tools/pull/111#pullrequestreview-52207165 it struck me that most of the time a column with double-width chars will have a number of entries with double-width content only, which suggests this simple optimization which checks for this using a `preg_match_all()` and just halves the length if so.
Crude benchmarking suggests a performance win if the percentage of such entries is above 10% or so, and only a small (2%) penalty if it's less than that, and a major win (100s of %) if it's anything above 50%, which I'm guessing is most likely to be the case - @miya0001 could you comment on whether this is likely in your experience for real data?
=> Optimize double-width safe_substr when all double-width.

.travis.yml, lib/cli/Shell.php, lib/cli/cli.php, lib/cli/table/Ascii.php, tests/bootstrap.php, tests/phpunit6-compat.php, tests/test-cli.php, tests/test-colors.php, tests/test-shell.php, tests/test-table.php
Issue https://github.com/wp-cli/php-cli-tools/issues/117
Uses `grapheme_substr()` and `preg_match()` in `safe_substr()` (and `grapheme_strlen()` and `preg_match_all()` in `safe_strlen()`) to deal with combining characters correctly, in a manner similar to that in `strwidth()`.
Refactors the East Asian Width stuff into a function `_safe_substr_eaw()` and adds `can_use_pcre_x()` helper to check for PCRE `\X` availability.
Removes use of `iconv()` as it varies widely over PHP versions and isn't easily tested and wasn't that useful anyway.
Incorporates the test data from @ShinichiNishikawa.
Fixes a gatepost error in `Ascii::setWidths()`.
Also tries `stty` as well in `Shell::columns()` as relying on the env var `COLUMNS` as introduced by me in https://github.com/wp-cli/php-cli-tools/pull/113 …
=> Use grapheme_substr & pcre_match in safe_substr for #117. Ascii::columns fix.

lib/cli/Colors.php, tests/test-cli.php
According to http://php.net/manual/en/function.str-pad.php
=> Added str_pad optional arguments

lib/cli/cli.php, tests/test-cli.php
Fixes wp-cli/db-command#54
Uses `preg_split()` instead of `preg_match()` with quantifiers in `safe_substr()` to avoid 65535 limit on quantifiers ([regexp.reference.repetition](http://php.net/manual/en/regexp.reference.repetition.php)), encountered for large strings.
Also normalizes the `$start` arg so its behaviour is the same no matter which substr method gets used. 
Also checks that `mb_substr()` is available before using it in `_safe_substr_eaw()`.
The following was noticed in testing and is unrelated so can do in a separate PR to reduce churn if desirable:
Also adds check that `$encoding` doesn't evaluate to false before passing it to `mbstring` functions as they can fail otherwise (seems to be system dependent).
=> Use preg_split instead of preg_match with quantifiers in safe_substr.

examples/common.php
Fixes #127 
Resolves off-by-1 error in `test_notify` function.
While changing the comparison operator fixes this issue, the need for a tick count parameter could be avoided altogether as described in this [issue comment](https://github.com/wp-cli/php-cli-tools/issues/127#issuecomment-370519406). Given the normal use case is to tick a number of times equal to the progress bar tick `total`, the passed progress bar object could be introspected if appropriately exposed.
=> fixing off-by-1 error in progress bar examples

examples/common.php, examples/progress.php, lib/cli/progress/Bar.php
As discussed in #125 
The tick method of `\cli\Notify::tick()` is augmented in its grandchild class, `\cli\Progress\Bar` to have an optional second parameter which updates its `_message` property. As items are processed, the message may be optionally changed to reflect the nature of the work being performed.
The current behavior of the progress bar suppresses any output until the first tick occurs. In use cases where the developer wishes to display the initial message and then alter it during the first tick, they should manually call the public `display()` method of the progress bar before work is performed and the tick occurs.
The use case of displaying a message describing work about to be performed would be better served by supplementing this updated `tick()` method with a setter for …
=> adding optional msg parameter to \cli\Progress\Bar::tick()

lib/cli/Streams.php
If user must enter zero, he can't exit from cycle.
=> Fix potential endless loop in prompt()

README.md
These should be `cli\notify`, not `cli\notifier`
=> Fix incorrect namespace for cli\notify\xxx

lib/cli/Shell.php, lib/cli/Streams.php
The function `stream_isatty()` ([PHP manual](https://www.php.net/manual/en/function.stream-isatty.php)) is available since PHP 7.2.0/8.0.
> Determines if stream stream refers to a valid terminal type device. This is a more portable version of posix_isatty(), since it works on Windows systems too.
This update also enables the use of an Output stream as an argument without triggering a warning, as in the folowing code.
```
define( 'STDOUT', fopen( 'php://output', 'w' ) );
var_dump(posix_isatty(STDOUT));
var_dump(stream_isatty(STDOUT));
=>
<b>Warning</b>:  posix_isatty(): could not use stream of type 'Output' in <b>/usr/local/var/www/wp-cli/php/boot-fpm.php</b> on line <b>22</b><br />
bool(false)
bool(false)
```
It is necessary to define `STDOUT` in this way while using the `fpm-fcgi` SAPI. …
=> Update TTY checks

examples/menu.php, lib/cli/arguments/HelpScreen.php
PHP 8.2 deprecates `"${var}"` string interpolation pattern.
This fixes all three of such occurrences in `wp-cli/php-cli-tools` package.
- [PHP 8.2: `${var}` string interpolation deprecated](https://php.watch/versions/8.2/${var}-string-interpolation-deprecated)
- [RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation)
=> [PHP 8.2] Fix `${var}` string interpolation deprecation

lib/cli/arguments/Lexer.php
added some `#[\ReturnTypeWillChange]` to suppress message like these :
```
Deprecated: Return type of cli\arguments\Lexer::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/wp-cli/php-cli-tools/lib/cli/arguments/Lexer.php on line 36
PHP Deprecated:  Return type of cli\arguments\Lexer::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/wp-cli/php-cli-tools/lib/cli/arguments/Lexer.php on line 64
```
=> remove deprecated warning message on php8.1

lib/cli/arguments/Lexer.php
avoid the following error in php 8.2.* : 
PHP Deprecated:  Creation of dynamic property cli\arguments\Lexer::$_item is deprecated in wp-cli/php-cli-tools/lib/cli/arguments/Lexer.php on line 113
=> fix PHP Deprecated:  Creation of dynamic property

lib/cli/table/Ascii.php
Fixes https://github.com/wp-cli/php-cli-tools/issues/159
Note: you'll need to resize your browser window in order to trigger the error warnings.
```
$  wp post create --post_title="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tem por por por"
$ wp post list
```
=> Prevent warnings in PHP 8.2 when `$col_values` is empty

lib/cli/Colors.php, lib/cli/cli.php
=> PHP 8.2: strwidth() & Colors::pad()/decolorize() should always work with a string

lib/cli/Streams.php, lib/cli/cli.php
I was confused by `phpstan analyse` output: "Parameter #2 $default of function cli\prompt expects string, false given." Soon I found out that problem is in type hinting for this function in `lib/cli/cli.php`. Hope my fix is helpful.
=> Fix type hinting for prompt function

composer.json
See https://github.com/wp-cli/wp-cli/issues/5480 and https://github.com/wp-cli/wp-cli/pull/5868 and https://github.com/wp-cli/wp-cli/issues/5859
=> Remove inexistent `post-install-cmd`

lib/cli/Notify.php
=> Use class instead of static variables for the speed measurement 

lib/cli/arguments/HelpScreen.php
=> Fix maxFlag to flagMax and maxOption to optionMax typos in HelpScreen class

lib/cli/table/Ascii.php
As of PHP 8.1, passing `null` to not explicitly nullable scalar parameters for PHP native functions is deprecated.
In this case, the `Test_Table_Ascii::testSpacingInTable()` method passes a row with the following values: `array('A2', '', ' C2', null)`. This then hits this deprecation in the `cli\table\Ascii::row()` method when calling the PHP native `str_replace()` function on line 141.
This can be seen when running the unit tests with `--display-deprecations`:
```
1) path/to/php-cli-tools/lib/cli/table/Ascii.php:141
str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
Triggered by:
* Test_Table_Ascii::testSpacingInTable
path/to/php-cli-tools/tests/Test_Table_Ascii.php:120
```
There are two options here:
1. Fix the test to pass an empty string instead …
=> PHP 8.1: fix "passing null to non-nullable"

lib/cli/Table.php
PHP 8.4 deprecates implicitly nullable parameters, i.e. typed parameters with a `null` default value, which are not explicitly declared as nullable.
As this code base still has a minimum supported PHP version of PHP 5.6, changing these parameters to explicitly nullable is not an option as that syntax was only introduced in PHP 7.1.
With that in mind, I'm proposing to change the default value of the parameters to comply with the type declaration.
Even though this is not a `final` class, this is not a breaking change for two reasons:
1. The signature check does not get applied to constructors.
2. Even if it did, default values can be different between parent vs child, as long as they comply with the expected type.
Ref: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
=> PHP 8.4 | Fix implicitly nullable parameters

examples/common.php
The `E_STRICT` constant is deprecated as of PHP 8.4 and will be removed in PHP 9.0 (commit went in today).
The error level hasn't been in use since PHP 8.0 anyway and was only barely still used in PHP 7.x, so removing the exclusion from the `error_reporting()` setting in the example code shouldn't really make any difference in practice.
Ref:
* https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant
=> PHP 8.4 | Example code: remove use of `E_STRICT`

lib/cli/table/Ascii.php
Before this code tried to replace newlines with empty spaces, but it didn't always work because the new value would only use the replaced string if additional wrapping needed to be done due to size constraints. This updates the code to properly handle new lines in all content by creating an extra row for each one, using the same logic that already existed for wrapping longer content.
See https://github.com/wp-cli/entity-command/issues/262 for an example of the currently broken behavior that this PR fixes
Example of new fixed output:
```
isla@Islas-MacBook-Pro ~/test $ wp post meta list 1
+---------+----------+--------------------+
| post_id | meta_key | meta_value         |
+---------+----------+--------------------+
| 1       | fruits   | apple              |
|         |          | …
```
=> Properly handle line breaks in column value

lib/cli/table/Ascii.php
While testing #179, I realized that tabs (`\t`) have always slightly messed up table formatting due to tab length.
By replacing them with spaces, the length calculation is correct again.
=> Replace tabs in tables with 4 spaces

lib/cli/table/Tabular.php
This adds the same functionality from both #179 and #181 to the tabular table output. In WP CLI behat tests, the 'table containing rows' check can only use tabular table output so we need to fix it here as well in order for tests to work (as seen in https://github.com/wp-cli/wp-cli/pull/6055).
Before:
```
post_id	meta_key	meta_value
1	foo	foo
1	fruits	apple
banana
mango
1	bar	br
```
After:
```
post_id	meta_key	meta_value
1	foo	foo
1	fruits	apple
banana
mango
1	bar	br
```
=> Support line breaks and tab replacement in tabular table values

lib/cli/table/Tabular.php, tests/Test_Table.php
To avoid deprecation warnings in PHP 8.1+:
```
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject)
of type array|string is deprecated in
/Users/isla/source/wp-cli-dev/php-cli-tools/lib/cli/table/Tabular.php on
line 30
```
I saw this while running tests for https://github.com/wp-cli/package-command/pull/197 where some rows of `wp package browse` look like:
```
array(4) {
[0]=>
string(22) "redkiwi-nl/localconfig"
[1]=>
NULL
[2]=>
string(0) ""
[3]=>
string(54) "0.1, 0.2.1, 0.2.2, 0.3, 0.3.1, 9999999-dev, dev-master"
}
array(4) {
[0]=>
string(18) "vccw/scaffold-vccw"
[1]=>
NULL
[2]=>
string(0) ""
[3]=>
string(84) "1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 9999999-dev, dev-master, dev-stable"
}
array(4) {
[0]=>
string(22) "welaika/wp-cli-db2utf8"
[1]=>
NULL
[2]=> …
```
=> Avoid deprecation warnings in newer PHP

composer.json, tests/Test_Arguments.php, tests/Test_Colors.php
Fixes branch alias config while at it
=> Update wp-cli-tests to v5
